### ISSUE TITLE
Add app versioning

### ISSUE THREAD

**Issue by jonoliver** [sparkbox/sparkpress-wordpress-starter#23]
Add ability to version app via a github workflow. 

## Questions
- How can we make app versioning useful for both our open source repo and a bespoke wordpress site based on it? 
- What versioning tool should be used?
   - [standard-version](https://github.com/conventional-changelog/standard-version) is deprecated
   - [semantic-release](https://github.com/semantic-release/semantic-release) is rigid and opinionated, difficult to customize for our needs
   - Consider creating a [standard-version](https://github.com/conventional-changelog/standard-version) of that we can use in other projects moving forward.

**Comment by dustin-jw** [comment]
Do we consider [Release Please](https://github.com/googleapis/release-please)? I know we briefly considered it elsewhere, but opted not to pursue it because of the PR workflow (if I remember correctly). It's the basis of #38 so I figure we should at least compare it to the other options here.
