### ISSUE TITLE
Add database import / export scripts

### ISSUE THREAD

**Issue by jonoliver** [sparkbox/sparkpress-wordpress-starter#32]

**Comment by dustin-jw** [comment]
I'm thinking for this we should have a pretty flexible process that makes it easy to import/export DBs without losing data or ending up with unwanted data. I found WordPress' XML import/export functionality to be pretty awkward and inconsistent, so we'd probably want to go with the DB dump path (just with less specificity).

I'm thinking we'd have this folder structure:
- `sql`
    - `exports`: SQL dumps explicitly generated by the developer
    - `backups`: SQL dumps automatically created when developers import a new DB
Then any `.sql` file added at the `sql` level would be what the import script looks for when importing a DB (maybe it grabs the last one if there are multiple? Or throws an error? So long as it doesn't require an explicit name)

Ideally the files would be timestamped and named in such a way that it's obvious when and how they were generated, such as:
- `db-export-2023-09-14T15-40-34_UTC.sql`
- `db-backup-2023-09-14T15-40-34_UTC.sql`

It would also be nice to be able to override the name while running the script, in case you want to label it as validation data for a PR or something more meaningful than a timestamp.

Ideal commands:
- `npm run import-db`: creates a timestamped backup of the existing DB (if one exists) and imports the DB from a `.sql` file
- `npm run export-db`: creates a timestamped `.sql` file
- `npm run export-db custom-post-validation`: creates a file called `custom-post-validation-<time-stamp>.sql` (having a timestamp is still nice in case there are multiple rounds of revision or you need to re-export for whatever reason)
