### ISSUE TITLE
Consolidate and audit documentation

### ISSUE THREAD

**Issue by dustin-jw** [sparkbox/sparkpress-wordpress-starter#91]
Currently, our `README` is very light on details and acts as essentially a table of contents that links to our other documentation. This makes finding information more difficult, as you have to guess which file has the info you need, then scan it for info, rinse and repeat until you find it (or give up). While putting everything in the `README` would make it a very long read, it would be easier for developers to scan for information that they need. With the right heading structure and keeping the table of contents at the start, it should still be possible to skip to relevant sections.

While we're at it, we should audit the existing docs for accuracy and fill in any gaps that we find (or at least create issues to fill in those gaps).

**Comment by jonoliver** [comment]
We should also update the readme to include a better description of the project, including some of the features.
